# Processes Special Issue "In Silico Metabolic Modeling and Engineering"
# Rule refrence:  (Christianson, 2017) https://doi.org/10.1021/acs.chemrev.7b00287
rule [
    ruleID "Diphosphate loss for nerolidyl diphosphate"
  left [
    node [ id  1 label "C" ]
    node [ id 16 label "O" ]
    edge [ source  1 target  2 label "=" ]
    edge [ source  3 target 16 label "-" ]    
  ]
  context [
    node [ id  2 label "C" ]
    node [ id  3 label "C" ]
    node [ id  4 label "C" ]
    node [ id  5 label "C" ]
    node [ id  6 label "C" ]
    node [ id  7 label "C" ]
    node [ id  8 label "C" ]
    node [ id  9 label "C" ]
    node [ id 10 label "C" ]
    node [ id 11 label "C" ]
    node [ id 12 label "C" ]
    node [ id 13 label "C" ]
    node [ id 14 label "C" ]
    node [ id 15 label "C" ]
    node [ id 17 label "P" ]
    node [ id 18 label "*" ]    
    edge [ source  2 target  3 label "-" ]    
    edge [ source  3 target  4 label "-" ]
    edge [ source  4 target  5 label "-" ]
    edge [ source  5 target  6 label "-" ]
    edge [ source  6 target  7 label "=" ]
    edge [ source  7 target  8 label "-" ]
    edge [ source  8 target  9 label "-" ]
    edge [ source  9 target 10 label "-" ]
    edge [ source 10 target 11 label "=" ]
    edge [ source 11 target 12 label "-" ]
    edge [ source 11 target 13 label "-" ]
    edge [ source  7 target 14 label "-" ]
    edge [ source  3 target 15 label "-" ]
    edge [ source 16 target 17 label "-" ]
    edge [ source 17 target 18 label "-" ]
  ]
  right [
    node [ id 1 label "C+" ]
    node [ id 16 label "O-" ]
    edge [ source  1 target 2 label "-" ]
  ]
]